### ISSUE TITLE
Page reload after trying to log user that not exist

### ISSUE THREAD

**Issue by KrystianKjjk** [CodersCrew/coderscamp-app#29] opened 2021-06-13 15:16 UTC
When user provide correct email and password, but it doesnt exist in db, some unnecessary behaviours happends: 
-page is reloaded, (or moved to '/home' probably)
-in localStorage id and token is written but with value "undefind"

Correct behaviour is show snackbar with correct information, that login failed

**Comment by kacper-cyra** [comment] 2021-06-13 16:48
Possible Duplicate of #18

**Closed** 2021-06-15 19:27 UTC
